In [ ]:
!pip install pyodbc
!pip install pandas
!pip install openpyxl

https://docs.microsoft.com/en-us/sql/machine-learning/data-exploration/python-dataframe-sql-server?view=sql-server-ver15

In [ ]:
import pyodbc
import pandas as pd
import numpy as np
import openpyxl

server = 'localhost\sqlexpress' 
database = 'Reciclaje_BD' 
username = 'username' 
password = 'yourpassword' 
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';Trusted_connection=yes')

MBIMETA = pd.read_excel('C:\\Users\\Fefi\\Desktop\\2022 Carga MBI v3.xlsx', sheet_name='MBI DIRECTORIO', header=4, usecols='A:AB', dtype='object')
#MBIMETA = pd.read_csv('C:\\Users\\Fefi\\Desktop\\2022 Carga MBI v31.csv')

In [ ]:
print (MBIMETA.dtypes)
MBIMETA.head(30)

In [54]:
from openpyxl import load_workbook
import pandas as pd

from datetime import date
from datetime import datetime

wb = load_workbook(filename='C:\\Users\\Fefi\\Desktop\\2022 Carga MBI v3.xlsx', data_only=True)
ws = wb['MBI META']

data = ws.values

columns1 = next(data)[0:]
columns2 = next(data)[1:]
columns3 = next(data)[2:]
columns4 = next(data)[3:]
columns5 = next(data)[0:28] # Encabezado fila 5

data = list(data)

df = pd.DataFrame([x if len(x) == 28 else x[:28] for x in data], columns=columns5, dtype='object') # Si hay mas columnas las ignora (ej: columna insert al final)
df = df.dropna() # Remover filas vacias (tabla del excel tiene filas vacias)


print (df.dtypes)
df.head(30)
#display(df)

SOCIEDAD                        object
CODCLIENTE                      object
CODPT                           object
AÑO                             object
MES                             object
CANT_PRES                       object
MONEDA                          object
INGRESOS_USD                    object
COSTO_USD                       object
TOTAL_AP_PRECIO_USD             object
TOTAL_AP_MK_USD                 object
MK_CORPORTATIVO_USD             object
TOTAL_COMISION_EXP_USD          object
TOTAL_GASTOS_ADUANA_USD         object
TOTAL_FLETE_INT_PUERTO_USD      object
TOTAL_COURIER_USD               object
TOTAL_SEGURO_CREDITO_EXP_USD    object
TOTAL_SEGURO_CREDITO_NAC_USD    object
TOTAL_OTROS_GASTOS_EXP_USD      object
TOTAL_COMISION_NAC_USD          object
TOTAL_FLETE_DESPACHO_NAC_USD    object
TOTAL_COMISION_INTERM_USD       object
TOTAL_SUPER_VARIABLE_USD        object
TOTAL_OTROS_GASTOS_NAC_USD      object
total_gdist_comis_usd           object
Gastos_de_Viaje_Expo            object
Gastos_de_Viaje_Nac             object
Cliente                         object
dtype: object

,SOCIEDAD,CODCLIENTE,CODPT,AÑO,MES,CANT_PRES,MONEDA,INGRESOS_USD,COSTO_USD,TOTAL_AP_PRECIO_USD,...,TOTAL_OTROS_GASTOS_EXP_USD,TOTAL_COMISION_NAC_USD,TOTAL_FLETE_DESPACHO_NAC_USD,TOTAL_COMISION_INTERM_USD,TOTAL_SUPER_VARIABLE_USD,TOTAL_OTROS_GASTOS_NAC_USD,total_gdist_comis_usd,Gastos_de_Viaje_Expo,Gastos_de_Viaje_Nac,Cliente
0,VSR,96568970-C,14005058-20,2022,Enero,1900-07-18 00:00:00,CLP,1917-07-30 22:40:00,1911-09-10 02:41:06.340000,00:00:00,...,00:00:00,00:00:00,1900-03-19 04:00:00,00:00:00,00:00:00,00:00:00,1900-05-08 18:26:53.332000,00:00:00,1900-01-28 11:41:26.022000,Distribución y Excelencia S.A.
1,VSR,96568970-C,14005057-20,2022,Enero,1900-02-28 00:00:00,CLP,1905-04-09 14:00:00,1903-04-15 18:50:17.371000,00:00:00,...,00:00:00,00:00:00,1900-01-23 18:00:00,00:00:00,00:00:00,00:00:00,1900-02-07 22:20:03.999000,00:00:00,1900-01-08 13:06:25.807000,Distribución y Excelencia S.A.
2,VSR,96568970-C,14005059-20,2022,Enero,1900-04-09 00:00:00,CLP,1908-10-14 23:20:00,1905-07-21 08:19:28.712000,00:00:00,...,00:00:00,00:00:00,1900-02-08 14:00:00,00:00:00,00:00:00,00:00:00,1900-03-04 21:13:26.666000,00:00:00,1900-01-14 05:50:43.011000,Distribución y Excelencia S.A.
3,VSR,96568970-C,14005080-18,2022,Enero,1900-01-10 00:00:00,CLP,1902-06-05 12:00:00,1901-04-26 08:20:11.853000,00:00:00,...,00:00:00,00:00:00,1900-01-03 23:00:00,00:00:00,00:00:00,00:00:00,1900-01-08 10:32:03.030000,00:00:00,1900-01-01 10:11:04.301000,Distribución y Excelencia S.A.
4,VSR,96568970-C,14005051-20,2022,Enero,1902-09-26 00:00:00,CLP,1963-12-10 13:20:00,1947-06-08 02:24:50.196000,00:00:00,...,00:00:00,00:00:00,1901-01-29 20:00:00,00:00:00,00:00:00,00:00:00,1901-09-09 16:43:51.027000,00:00:00,1900-05-21 10:27:10.110000,Distribución y Excelencia S.A.
5,VSR,96568970-C,14005050-21,2022,Enero,1902-09-26 00:00:00,CLP,1963-12-10 13:20:00,1943-08-09 00:23:08.973000,00:00:00,...,00:00:00,00:00:00,1901-01-29 20:00:00,00:00:00,00:00:00,00:00:00,1901-09-09 16:43:51.027000,00:00:00,1900-05-21 10:27:10.110000,Distribución y Excelencia S.A.
6,VSR,96568970-C,14005052-21,2022,Enero,1902-09-26 00:00:00,CLP,1963-12-10 13:20:00,1946-01-04 02:01:59.303000,00:00:00,...,00:00:00,00:00:00,1901-01-29 20:00:00,00:00:00,00:00:00,00:00:00,1901-09-09 16:43:51.027000,00:00:00,1900-05-21 10:27:10.110000,Distribución y Excelencia S.A.
7,VSR,96568970-C,14005054-20,2022,Enero,1900-07-08 09:36:00,CLP,1912-03-03 21:32:48,1906-11-19 23:02:33.806000,00:00:00,...,00:00:00,00:00:00,1900-03-15 08:48:00,00:00:00,00:00:00,00:00:00,1900-04-26 19:11:54.067000,00:00:00,1900-01-27 02:52:24.293000,Distribución y Excelencia S.A.
8,VSR,96568970-C,14004702-19,2022,Enero,1900-02-28 00:00:00,CLP,1903-11-01 08:00:00,1901-12-24 19:32:15.414000,00:00:00,...,00:00:00,00:00:00,1900-01-23 18:00:00,00:00:00,00:00:00,00:00:00,1900-02-06 02:55:25.862000,00:00:00,1900-01-08 13:06:25.807000,Distribución y Excelencia S.A.
9,VSR,96568970-C,14005055-20,2022,Enero,1900-06-28 00:00:00,CLP,1911-07-05 00:00:00,1906-10-24 05:49:44.073000,00:00:00,...,00:00:00,00:00:00,1900-03-11 06:00:00,00:00:00,00:00:00,00:00:00,1900-04-20 08:46:17.585000,00:00:00,1900-01-25 15:19:17.420000,Distribución y Excelencia S.A.
10,VSR,96568970-C,14005123-21,2022,Enero,1900-02-09 00:00:00,CLP,1902-07-22 05:20:00,1901-10-20 16:04:28.213000,00:00:00,...,00:00:00,00:00:00,1900-01-15 20:00:00,00:00:00,00:00:00,00:00:00,1900-01-24 17:56:57.241000,00:00:00,1900-01-05 16:44:17.204000,Distribución y Excelencia S.A.
11,VSR,96568970-C,14005078-18,2022,Enero,1900-01-20 00:00:00,CLP,1903-01-16 00:40:00,1901-07-07 16:00:38.283000,00:00:00,...,00:00:00,00:00:00,1900-01-07 22:00:00,00:00:00,00:00:00,00:00:00,1900-01-14 14:16:31.297000,00:00:00,1900-01-02 20:22:08.602000,Distribución y Excelencia S.A.
12,VSR,96568970-C,14005076-18,2022,Enero,1900-01-20 00:00:00,CLP,1903-01-16 00:40:00,1901-11-21 14:01:21.912000,00:00:00,...,00:00:00,00:00:00,1900-01-07 22:00:00,00:00:00,00:00:00,00:00:00,1900-01-14 14:16:31.297000,00:00:00,1900-01-02 20:22:08.602000,Distribución y Excelencia S.A.
13,VSR,96568970-C,14005075-18,2022,Enero,1900-01-20 00:00:00,CLP,1903-01-16 00:40:00,1901-09-11 17:32:26.789000,00:00:00,...,00:00:00,00:00:00,1900-01-07 22:00:00,00:00:00,00:00:00,00:00:00,1900-01-14 14:16:31.297000,00:00:00,1900-01-02 20:22:08.602000,Distribución y Excelencia S.A.
14,VSR,Cripton_China,14004807-18,2022,Enero,1900-01-02 19:23:31.200000,USD,1901-11-03 22:04:48,1900-06-23 01:15:19.006000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-02-07 19:51:31.654000,1900-01-12 15:39:52.855000,00:00:00,Cripton China
15,VSR,Cripton_China,14004807-18,2022,Enero,1900-01-02 03:50:24,USD,1901-12-02 00:00:00,1900-06-22 21:33:41.980000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-02-05 00:10:49.926000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
16,VSR,Cripton_China,14005073-18,2022,Enero,1900-01-06 11:31:12,USD,1903-03-11 09:36:00,1901-05-08 11:41:09.791000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-03-16 14:22:26.486000,1900-01-29 04:45:52.741000,00:00:00,Cripton China
17,VSR,Cripton_China,14004339-19,2022,Enero,1900-03-04 19:12:00,USD,1907-12-25 00:00:00,1903-05-30 11:15:31.326000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1901-04-17 10:10:48.003000,1900-10-17 23:38:47.414000,00:00:00,Cripton China
18,VSR,Cripton_China,14004806-17,2022,Enero,1900-01-21 14:24:00,USD,1904-09-23 00:00:00,1901-08-30 20:40:23.528000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-07-01 02:11:41.408000,1900-04-06 07:52:55.805000,00:00:00,Cripton China
19,VSR,Cripton_China,14004965-17,2022,Enero,1900-01-02 03:50:24,USD,1900-08-03 00:00:00,1900-05-16 13:51:50.840000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-01-19 18:05:37.878000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
20,VSR,Cripton_China,14004992-19,2022,Enero,1900-02-12 04:48:00,USD,1904-09-23 00:00:00,1902-05-15 01:48:34.651000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-11-03 09:24:53.314000,1900-07-12 15:45:51.609000,00:00:00,Cripton China
21,VSR,Cripton_China,14004971-20,2022,Enero,1900-09-15 04:48:00,USD,1917-09-27 00:00:00,1912-02-03 04:27:20.324000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1904-09-15 07:47:43.504000,1903-03-12 22:35:09.656000,00:00:00,Cripton China
22,VSR,Cripton_China,14004990-20,2022,Enero,1900-04-21 07:40:48,USD,1909-03-22 14:24:00,1904-10-13 05:00:33.157000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1902-02-02 06:08:41.440000,1901-05-20 02:35:14.184000,00:00:00,Cripton China
23,VSR,Cripton_China,14005163-18,2022,Enero,1900-01-10 19:12:00,USD,1902-05-13 00:00:00,1901-08-06 03:59:58.220000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-03-31 13:05:50.704000,1900-02-17 15:56:27.902000,00:00:00,Cripton China
24,VSR,Cripton_China,14005143-17,2022,Enero,1900-01-17 06:43:12,USD,1902-11-01 19:12:00,1901-10-13 09:08:42.257000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-05-13 21:57:39.226000,1900-03-17 20:42:20.644000,00:00:00,Cripton China
25,VSR,Cripton_China,14005087-20,2022,Enero,1900-01-21 14:24:00,USD,1903-04-02 00:00:00,1901-03-18 04:05:36.693000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-06-13 00:45:54.689000,1900-04-06 07:52:55.805000,00:00:00,Cripton China
26,VSR,Cripton_China,14005080-18,2022,Enero,1900-01-02 03:50:24,USD,1900-09-15 04:48:00,1900-04-13 04:29:19.360000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-01-21 04:46:05.616000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
27,VSR,Cripton_China,14004879-18,2022,Enero,1900-01-02 03:50:24,USD,1900-09-15 04:48:00,1900-07-06 17:32:57.782000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-01-21 04:46:05.616000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
28,VSR,Cripton_China,14005089-20,2022,Enero,1900-04-17 00:00:00,USD,1911-10-29 00:00:00,1905-01-04 07:23:39.790000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1902-02-08 23:32:13.285000,1901-04-30 15:24:39.023000,00:00:00,Cripton China
29,VSR,Cripton_China,14005043-17,2022,Enero,1900-01-17 06:43:12,USD,1903-04-23 14:24:00,1901-06-12 14:20:33.954000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-05-19 16:39:30.176000,1900-03-17 20:42:20.644000,00:00:00,Cripton China

In [55]:
from datetime import date
from datetime import datetime

# Funcion para transformar las columnas que vienen con formato fecha a int
# a: nombre columna
# b: numero que se le suma porque por algun motivo le faltan (puede que sea por aproximacion)
def fu(a,b):
    for i in df.index:
        if len(str(df.at[i, a])) != None:
            #try:
                f_date = datetime(1899,12,30,0,0,0,0)
                #l_date = (df.at[i, a].datetime())
                l_date = pd.to_datetime(df.at[i, a], format="%f")
                delta = l_date - f_date
                df.at[i, a] = (delta.days+b) # +b
            #except AttributeError:
                df.at[i, a] = '-'

In [56]:
fu('CANT_PRES',0)
fu('INGRESOS_USD',0)
fu('COSTO_USD',0)
fu('TOTAL_AP_PRECIO_USD',0)
fu('TOTAL_AP_MK_USD',0)
fu('MK_CORPORTATIVO_USD',0)
fu('TOTAL_COMISION_EXP_USD',0)
fu('TOTAL_GASTOS_ADUANA_USD',0)
fu('TOTAL_FLETE_INT_PUERTO_USD',0)
fu('TOTAL_COURIER_USD',0)
fu('TOTAL_SEGURO_CREDITO_EXP_USD',0)
fu('TOTAL_SEGURO_CREDITO_NAC_USD',0)
fu('TOTAL_OTROS_GASTOS_EXP_USD',0)
fu('TOTAL_COMISION_NAC_USD',0)
fu('TOTAL_FLETE_DESPACHO_NAC_USD',0)
fu('TOTAL_COMISION_INTERM_USD',0)
fu('TOTAL_SUPER_VARIABLE_USD',0)
fu('TOTAL_OTROS_GASTOS_NAC_USD',0)
fu('total_gdist_comis_usd',0)
fu('Gastos_de_Viaje_Expo',0)
fu('Gastos_de_Viaje_Nac',0)

ValueError: unconverted data remains: -04-27 10:50:52.800000

In [57]:
#print (df.dtypes)
#display(df)
df.head(30)

,SOCIEDAD,CODCLIENTE,CODPT,AÑO,MES,CANT_PRES,MONEDA,INGRESOS_USD,COSTO_USD,TOTAL_AP_PRECIO_USD,...,TOTAL_OTROS_GASTOS_EXP_USD,TOTAL_COMISION_NAC_USD,TOTAL_FLETE_DESPACHO_NAC_USD,TOTAL_COMISION_INTERM_USD,TOTAL_SUPER_VARIABLE_USD,TOTAL_OTROS_GASTOS_NAC_USD,total_gdist_comis_usd,Gastos_de_Viaje_Expo,Gastos_de_Viaje_Nac,Cliente
0,VSR,96568970-C,14005058-20,2022,Enero,-,CLP,-,1911-09-10 02:41:06.340000,00:00:00,...,00:00:00,00:00:00,1900-03-19 04:00:00,00:00:00,00:00:00,00:00:00,1900-05-08 18:26:53.332000,00:00:00,1900-01-28 11:41:26.022000,Distribución y Excelencia S.A.
1,VSR,96568970-C,14005057-20,2022,Enero,-,CLP,-,1903-04-15 18:50:17.371000,00:00:00,...,00:00:00,00:00:00,1900-01-23 18:00:00,00:00:00,00:00:00,00:00:00,1900-02-07 22:20:03.999000,00:00:00,1900-01-08 13:06:25.807000,Distribución y Excelencia S.A.
2,VSR,96568970-C,14005059-20,2022,Enero,-,CLP,-,1905-07-21 08:19:28.712000,00:00:00,...,00:00:00,00:00:00,1900-02-08 14:00:00,00:00:00,00:00:00,00:00:00,1900-03-04 21:13:26.666000,00:00:00,1900-01-14 05:50:43.011000,Distribución y Excelencia S.A.
3,VSR,96568970-C,14005080-18,2022,Enero,-,CLP,-,1901-04-26 08:20:11.853000,00:00:00,...,00:00:00,00:00:00,1900-01-03 23:00:00,00:00:00,00:00:00,00:00:00,1900-01-08 10:32:03.030000,00:00:00,1900-01-01 10:11:04.301000,Distribución y Excelencia S.A.
4,VSR,96568970-C,14005051-20,2022,Enero,-,CLP,-,1947-06-08 02:24:50.196000,00:00:00,...,00:00:00,00:00:00,1901-01-29 20:00:00,00:00:00,00:00:00,00:00:00,1901-09-09 16:43:51.027000,00:00:00,1900-05-21 10:27:10.110000,Distribución y Excelencia S.A.
5,VSR,96568970-C,14005050-21,2022,Enero,-,CLP,-,1943-08-09 00:23:08.973000,00:00:00,...,00:00:00,00:00:00,1901-01-29 20:00:00,00:00:00,00:00:00,00:00:00,1901-09-09 16:43:51.027000,00:00:00,1900-05-21 10:27:10.110000,Distribución y Excelencia S.A.
6,VSR,96568970-C,14005052-21,2022,Enero,-,CLP,-,1946-01-04 02:01:59.303000,00:00:00,...,00:00:00,00:00:00,1901-01-29 20:00:00,00:00:00,00:00:00,00:00:00,1901-09-09 16:43:51.027000,00:00:00,1900-05-21 10:27:10.110000,Distribución y Excelencia S.A.
7,VSR,96568970-C,14005054-20,2022,Enero,-,CLP,-,1906-11-19 23:02:33.806000,00:00:00,...,00:00:00,00:00:00,1900-03-15 08:48:00,00:00:00,00:00:00,00:00:00,1900-04-26 19:11:54.067000,00:00:00,1900-01-27 02:52:24.293000,Distribución y Excelencia S.A.
8,VSR,96568970-C,14004702-19,2022,Enero,-,CLP,-,1901-12-24 19:32:15.414000,00:00:00,...,00:00:00,00:00:00,1900-01-23 18:00:00,00:00:00,00:00:00,00:00:00,1900-02-06 02:55:25.862000,00:00:00,1900-01-08 13:06:25.807000,Distribución y Excelencia S.A.
9,VSR,96568970-C,14005055-20,2022,Enero,-,CLP,-,1906-10-24 05:49:44.073000,00:00:00,...,00:00:00,00:00:00,1900-03-11 06:00:00,00:00:00,00:00:00,00:00:00,1900-04-20 08:46:17.585000,00:00:00,1900-01-25 15:19:17.420000,Distribución y Excelencia S.A.
10,VSR,96568970-C,14005123-21,2022,Enero,-,CLP,-,1901-10-20 16:04:28.213000,00:00:00,...,00:00:00,00:00:00,1900-01-15 20:00:00,00:00:00,00:00:00,00:00:00,1900-01-24 17:56:57.241000,00:00:00,1900-01-05 16:44:17.204000,Distribución y Excelencia S.A.
11,VSR,96568970-C,14005078-18,2022,Enero,-,CLP,-,1901-07-07 16:00:38.283000,00:00:00,...,00:00:00,00:00:00,1900-01-07 22:00:00,00:00:00,00:00:00,00:00:00,1900-01-14 14:16:31.297000,00:00:00,1900-01-02 20:22:08.602000,Distribución y Excelencia S.A.
12,VSR,96568970-C,14005076-18,2022,Enero,-,CLP,-,1901-11-21 14:01:21.912000,00:00:00,...,00:00:00,00:00:00,1900-01-07 22:00:00,00:00:00,00:00:00,00:00:00,1900-01-14 14:16:31.297000,00:00:00,1900-01-02 20:22:08.602000,Distribución y Excelencia S.A.
13,VSR,96568970-C,14005075-18,2022,Enero,-,CLP,-,1901-09-11 17:32:26.789000,00:00:00,...,00:00:00,00:00:00,1900-01-07 22:00:00,00:00:00,00:00:00,00:00:00,1900-01-14 14:16:31.297000,00:00:00,1900-01-02 20:22:08.602000,Distribución y Excelencia S.A.
14,VSR,Cripton_China,14004807-18,2022,Enero,-,USD,-,1900-06-23 01:15:19.006000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-02-07 19:51:31.654000,1900-01-12 15:39:52.855000,00:00:00,Cripton China
15,VSR,Cripton_China,14004807-18,2022,Enero,-,USD,-,1900-06-22 21:33:41.980000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-02-05 00:10:49.926000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
16,VSR,Cripton_China,14005073-18,2022,Enero,-,USD,-,1901-05-08 11:41:09.791000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-03-16 14:22:26.486000,1900-01-29 04:45:52.741000,00:00:00,Cripton China
17,VSR,Cripton_China,14004339-19,2022,Enero,-,USD,-,1903-05-30 11:15:31.326000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1901-04-17 10:10:48.003000,1900-10-17 23:38:47.414000,00:00:00,Cripton China
18,VSR,Cripton_China,14004806-17,2022,Enero,-,USD,-,1901-08-30 20:40:23.528000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-07-01 02:11:41.408000,1900-04-06 07:52:55.805000,00:00:00,Cripton China
19,VSR,Cripton_China,14004965-17,2022,Enero,-,USD,-,1900-05-16 13:51:50.840000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-01-19 18:05:37.878000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
20,VSR,Cripton_China,14004992-19,2022,Enero,-,USD,-,1902-05-15 01:48:34.651000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-11-03 09:24:53.314000,1900-07-12 15:45:51.609000,00:00:00,Cripton China
21,VSR,Cripton_China,14004971-20,2022,Enero,-,USD,-,1912-02-03 04:27:20.324000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1904-09-15 07:47:43.504000,1903-03-12 22:35:09.656000,00:00:00,Cripton China
22,VSR,Cripton_China,14004990-20,2022,Enero,-,USD,-,1904-10-13 05:00:33.157000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1902-02-02 06:08:41.440000,1901-05-20 02:35:14.184000,00:00:00,Cripton China
23,VSR,Cripton_China,14005163-18,2022,Enero,-,USD,-,1901-08-06 03:59:58.220000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-03-31 13:05:50.704000,1900-02-17 15:56:27.902000,00:00:00,Cripton China
24,VSR,Cripton_China,14005143-17,2022,Enero,-,USD,-,1901-10-13 09:08:42.257000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-05-13 21:57:39.226000,1900-03-17 20:42:20.644000,00:00:00,Cripton China
25,VSR,Cripton_China,14005087-20,2022,Enero,-,USD,-,1901-03-18 04:05:36.693000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-06-13 00:45:54.689000,1900-04-06 07:52:55.805000,00:00:00,Cripton China
26,VSR,Cripton_China,14005080-18,2022,Enero,-,USD,-,1900-04-13 04:29:19.360000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-01-21 04:46:05.616000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
27,VSR,Cripton_China,14004879-18,2022,Enero,-,USD,-,1900-07-06 17:32:57.782000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-01-21 04:46:05.616000,1900-01-09 17:35:17.580000,00:00:00,Cripton China
28,VSR,Cripton_China,14005089-20,2022,Enero,-,USD,-,1905-01-04 07:23:39.790000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1902-02-08 23:32:13.285000,1901-04-30 15:24:39.023000,00:00:00,Cripton China
29,VSR,Cripton_China,14005043-17,2022,Enero,-,USD,-,1901-06-12 14:20:33.954000,00:00:00,...,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1900-05-19 16:39:30.176000,1900-03-17 20:42:20.644000,00:00:00,Cripton China

In [9]:
df.head(30)

,SOCIEDAD,CODCLIENTE,CODPT,AÑO,MES,CANT_PRES,MONEDA,INGRESOS_USD,COSTO_USD,TOTAL_AP_PRECIO_USD,...,TOTAL_OTROS_GASTOS_EXP_USD,TOTAL_COMISION_NAC_USD,TOTAL_FLETE_DESPACHO_NAC_USD,TOTAL_COMISION_INTERM_USD,TOTAL_SUPER_VARIABLE_USD,TOTAL_OTROS_GASTOS_NAC_USD,total_gdist_comis_usd,Gastos_de_Viaje_Expo,Gastos_de_Viaje_Nac,Cliente
0,VSR,96568970-C,14005058-20,2022.0,Enero,200,CLP,6421,4271,-,...,-,-,79,-,-,-,129,-,29,Distribución y Excelencia S.A.
1,VSR,96568970-C,14005057-20,2022.0,Enero,60,CLP,1926,1201,-,...,-,-,24,-,-,-,39,-,9,Distribución y Excelencia S.A.
2,VSR,96568970-C,14005059-20,2022.0,Enero,100,CLP,3210,2029,-,...,-,-,40,-,-,-,64,-,15,Distribución y Excelencia S.A.
3,VSR,96568970-C,14005080-18,2022.0,Enero,11,CLP,887,482,-,...,-,-,4,-,-,-,9,-,2,Distribución y Excelencia S.A.
4,VSR,96568970-C,14005051-20,2022.0,Enero,1000,CLP,23355,17326,-,...,-,-,395,-,-,-,618,-,142,Distribución y Excelencia S.A.
5,VSR,96568970-C,14005050-21,2022.0,Enero,1000,CLP,23355,15927,-,...,-,-,395,-,-,-,618,-,142,Distribución y Excelencia S.A.
6,VSR,96568970-C,14005052-21,2022.0,Enero,1000,CLP,23355,16806,-,...,-,-,395,-,-,-,618,-,142,Distribución y Excelencia S.A.
7,VSR,96568970-C,14005054-20,2022.0,Enero,190,CLP,4446,2515,-,...,-,-,75,-,-,-,117,-,28,Distribución y Excelencia S.A.
8,VSR,96568970-C,14004702-19,2022.0,Enero,60,CLP,1401,724,-,...,-,-,24,-,-,-,38,-,9,Distribución y Excelencia S.A.
9,VSR,96568970-C,14005055-20,2022.0,Enero,180,CLP,4204,2489,-,...,-,-,71,-,-,-,111,-,26,Distribución y Excelencia S.A.
10,VSR,96568970-C,14005123-21,2022.0,Enero,41,CLP,934,659,-,...,-,-,16,-,-,-,25,-,6,Distribución y Excelencia S.A.
11,VSR,96568970-C,14005078-18,2022.0,Enero,21,CLP,1112,554,-,...,-,-,8,-,-,-,15,-,3,Distribución y Excelencia S.A.
12,VSR,96568970-C,14005076-18,2022.0,Enero,21,CLP,1112,691,-,...,-,-,8,-,-,-,15,-,3,Distribución y Excelencia S.A.
13,VSR,96568970-C,14005075-18,2022.0,Enero,21,CLP,1112,620,-,...,-,-,8,-,-,-,15,-,3,Distribución y Excelencia S.A.
14,VSR,Cripton_China,14004807-18,2022.0,Enero,3,USD,673,175,-,...,-,-,-,-,-,-,39,13,-,Cripton China
15,VSR,Cripton_China,14004807-18,2022.0,Enero,3,USD,702,174,-,...,-,-,-,-,-,-,37,10,-,Cripton China
16,VSR,Cripton_China,14005073-18,2022.0,Enero,7,USD,1166,494,-,...,-,-,-,-,-,-,76,30,-,Cripton China
17,VSR,Cripton_China,14004339-19,2022.0,Enero,64,USD,2916,1246,-,...,-,-,-,-,-,-,473,291,-,Cripton China
18,VSR,Cripton_China,14004806-17,2022.0,Enero,22,USD,1728,608,-,...,-,-,-,-,-,-,183,97,-,Cripton China
19,VSR,Cripton_China,14004965-17,2022.0,Enero,3,USD,216,137,-,...,-,-,-,-,-,-,20,10,-,Cripton China
20,VSR,Cripton_China,14004992-19,2022.0,Enero,44,USD,1728,866,-,...,-,-,-,-,-,-,308,194,-,Cripton China
21,VSR,Cripton_China,14004971-20,2022.0,Enero,259,USD,6480,4417,-,...,-,-,-,-,-,-,1720,1167,-,Cripton China
22,VSR,Cripton_China,14004990-20,2022.0,Enero,112,USD,3369,1748,-,...,-,-,-,-,-,-,764,506,-,Cripton China
23,VSR,Cripton_China,14005163-18,2022.0,Enero,11,USD,864,584,-,...,-,-,-,-,-,-,91,49,-,Cripton China
24,VSR,Cripton_China,14005143-17,2022.0,Enero,18,USD,1036,652,-,...,-,-,-,-,-,-,134,77,-,Cripton China
25,VSR,Cripton_China,14005087-20,2022.0,Enero,22,USD,1188,443,-,...,-,-,-,-,-,-,165,97,-,Cripton China
26,VSR,Cripton_China,14005080-18,2022.0,Enero,3,USD,259,104,-,...,-,-,-,-,-,-,22,10,-,Cripton China
27,VSR,Cripton_China,14004879-18,2022.0,Enero,3,USD,259,188,-,...,-,-,-,-,-,-,22,10,-,Cripton China
28,VSR,Cripton_China,14005089-20,2022.0,Enero,108,USD,4320,1831,-,...,-,-,-,-,-,-,770,486,-,Cripton China
29,VSR,Cripton_China,14005043-17,2022.0,Enero,18,USD,1209,529,-,...,-,-,-,-,-,-,140,77,-,Cripton China

In [201]:
from datetime import date
from datetime import datetime


f_date = date(1900,1,1)
l_date = (df["INGRESOS_USD"][2].date())


delta = l_date - f_date
print(delta.days+3)

3211

In [ ]:
#df = pd.DataFrame([x if len(x) == 28 else x[:28] for x in data], columns=columns5)
#print (df.dtypes)

df.loc[:, 'CANT_PRES'] = (df["CANT_PRES"].to_pydatetime().date())

df.head(30)

In [ ]:
cursor = cnxn.cursor()

# Insert Dataframe into SQL Server:
for index, row in MBIMETA.iterrows():
     cursor.execute("INSERT INTO TABLA_PRESUPUESTO_COMERCIAL VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", row.SOCIEDAD,row.CODCLIENTE,row.CODPT,row.AÑO,row.MES,row.CANT_PRES,row.MONEDA,row.INGRESOS_USD,row.COSTO_USD,row.TOTAL_AP_PRECIO_USD,row.TOTAL_AP_MK_USD,row.MK_CORPORTATIVO_USD,row.TOTAL_COMISION_EXP_USD,row.TOTAL_GASTOS_ADUANA_USD,row.TOTAL_FLETE_INT_PUERTO_USD,row.TOTAL_COURIER_USD,row.TOTAL_SEGURO_CREDITO_EXP_USD,row.TOTAL_SEGURO_CREDITO_NAC_USD,row.TOTAL_OTROS_GASTOS_EXP_USD,row.TOTAL_COMISION_NAC_USD,row.TOTAL_FLETE_DESPACHO_NAC_USD,row.TOTAL_COMISION_INTERM_USD,row.TOTAL_SUPER_VARIABLE_USD,row.TOTAL_OTROS_GASTOS_NAC_USD,row.total_gdist_comis_usd,row.Gastos_de_Viaje_Expo,row.Gastos_de_Viaje_Nac)
cnxn.commit()

cursor.close()

In [ ]:

#MBIMETA["CANT_PRES"] = pd.to_numeric(MBIMETA["CANT_PRES"])
#MBIMETA.["CANT_PRES"] = MBIMETA.["CANT_PRES"].astype('datetime64')
#MBIMETA["Gastos_de_Viaje_Nac"] = pd.to_numeric(MBIMETA["Gastos_de_Viaje_Nac"])
#MBIMETA = MBIMETA.astype(dtype= {"Gastos_de_Viaje_Nac":"object"})
print(MBIMETA.values)
MBIMETA.head(10)

In [52]:
MBIMETA.to_csv("./data.csv", sep=",")

In [ ]:
#Hola :)

#push

#botella

#estefania